### PR TITLE
Update reactor bom version to Californium-SR3

### PR DESCRIPTION
**Pull request by aharonha**

### CODE REVIEW

**Comment by aharonha** [comment]
Please release a version with this change

**Comment by yschimke** [comment]
Some google fun from the future, 11 hours from now

image

**Comment by aharonha** [comment]
@OlegDokuka do you mean that I should set the next version in this PR?

**Comment by OlegDokuka** [comment]
@aharonha I mean that you could exclude netty and Rector-xx dependencies from the original RSocket-Core on to the required ones while this PR is unmerged.

**Comment by aharonha** [comment]
The build was failed. I believe that's my _fault_ so I should open a new PR for upgrading the version

**Pull request merged**
