### PR TITLE
update build dependencies

### PR DESCRIPTION
**Pull request by qweek**
plugins: com.jfrog.artifactory 4.5.2
dependencies: jsr305 3.0.2, aeron 1.4.1, spectator 0.57.1, hdrHistogram 2.1.9, jackson 2.9.1, commons-lang3 3.6, airline 0.8, rxjava 2.1.3, mockito 2.10.0, jmh 1.19

### CODE REVIEW

**Comment by qweek** [comment]
Please check #383 first

**Comment by yschimke** [comment]
@qweek nice! Thanks for the general cleanup also.

**Comment by robertroeser** [comment]
@qweek @yschimke Why are the version the version not inline with the includes? Can you put this back please.

**Comment by yschimke** [comment]
@robertroeser I don't have a strong opinion on this, but this is pretty common for gradle projects.

To be clear you mean, you would prefer to see

compile "io.netty:netty-transport-native-epoll:4.1.15.Final"

**Comment by robertroeser** [comment]
Yes because you don't have to scroll to find what version you are using.

**Pull request merged**
