### PR TITLE
extract java, google java format and jmh to separate script plugins

### PR DESCRIPTION
**Pull request by qweek**
configuration:
- explicitly set gradle version and distribution type (upgrade later)

versions:
-  move dependency versions to separate file

java:
-  set encoding to UTF-8
-  disable specific compiler warnings (fix later)

codestyle:
-  set google java format version for plugin (upgrade later)
-  run formatting before compilation

benchmark:
-  exclude test dependencies from jmh jar
-  fix duplicate jmh generated classes (jmh-generated-classes, jmh-generated-sources)
-  fix broken jmh metadata files (BenchmarkList, CompilerHints)
-  fix jmh command line jar (inline dependencies with shadow plugin)
-  fix jmh task for root scope (stop generate dummy jar)
-  cleanup redundant out directory generated by IDEA
-  remove slf4j and log4j dependencies (replace with slf4j-nop logger)
-  add visual jmh report

### CODE REVIEW

**Comment by qweek** [comment]
cli example:
`java -jar build/libs/rsocket-core-0.9-SNAPSHOT-jmh.jar io.rsocket.RSocketPerf.fireAndForgetHello -t 2`

**Comment by qweek** [comment]
known issues:
- Exception while trying to acquire the JMH lock on Windows (C:\Windows/jmh.lock)

workaround:
- Run IDE as administrator

**Comment by yschimke** [comment]
cc @robertroeser 

I'll defer to Robert here.  I got the gradle scripts working for snapshots and releases, but apart from that, I'm not very fussed about the structure if it's working.

**Comment by robertroeser** [comment]
I'd prefer to leave it in one file. It works now, and it's easy to find what we're doing. I don't want to dig through a bunch of different files to figure out what the version of something is, or what configuration we're using.

**Comment by qweek** [comment]
If you wish I can merge this changes to main build.gradle file

**Pull request closed without merging**
