### PR TITLE
Ensure Subscriber is removed from sendingSubscriptions

### PR DESCRIPTION
**Pull request by rstoyanchev**
Fix for #961.

### CODE REVIEW

**Review by OlegDokuka — CHANGES_REQUESTED** [review]
Let's do it a little differently. Let's remove the subscriber right immediately at the `onNext` method. Spec says that in the case of `NEXT_COMPLETE` no frames should be sent.

Thus, we should consider only 3 possible outcomes:
```
onNext -> remove subscriber and send the NEXT_COMPLETE frame
only onComplete -> remove subscriber and send the COMPLETE frame
only onError -> remove subscriber and send the ERROR frame
```

if 

```
onNext + onComplete (do nothing at onComplete)
onNext + onError (drop error at onError)
```

**Comment by rstoyanchev** [comment]
> Let's do it a little differently.

Good idea, I've updated the PR accordingly.

**Review by OlegDokuka — APPROVED** [review]
LGTM

**Review by OlegDokuka — APPROVED** [review]
LGTM

**Comment by linux-china** [comment]
@OlegDokuka  could you release 1.0.4 to include this bug fix?   it's very important for Spring Boot 2.3.X.

**Pull request merged**
