### PR TITLE
add tck tests on travis push

### PR DESCRIPTION
**Pull request by ragansa**
Causes TCK tests to run when a new pull request is made

### CODE REVIEW

**Comment by yschimke** [comment]
LGTM - I'd like an ACK before merging from @rdegnan @robertroeser that they are bought into keeping these working

**Comment by robertroeser** [comment]
I would prefer to make this not use RXJava 2 TestSubscriber first, and make it a gradle task - not a separate main method -  before it is run all the time.

**Comment by rdegnan** [comment]
Agreed, I can take a stab at refactoring to add a gradle task/remove the
use of TestSubscriber.

On May 10, 2017, at 3:57 PM, Robert Roeser <notifications@github.com> wrote:

I would prefer to make this not use RXJava 2 TestSubscriber first, and make
it a gradle task - not a separate main method - before it is run all the
time.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ReactiveSocket/reactivesocket-java/pull/282#issuecomment-300635864>,
or mute the thread

**Comment by yschimke** [comment]
@rdegnan @robertroeser can we land this and refactor the main method later?

**Comment by robertroeser** [comment]
@yschimke yeah that's fine.

**Comment by robertroeser** [comment]
@yschimke the server start blocks - this probably needs to be refactor to emit a Mono that the RSocketFactory produces. When the Mono completes you can start the test. That probably needs to happen for this to work.

**Comment by yschimke** [comment]
This code has been refactored to use @Test instead

**Pull request closed without merging**
