### PR TITLE
update jmh plugin settings

### PR DESCRIPTION
**Pull request by qweek**
exclude test dependencies from jmh jar
fix duplicate jmh generated classes (jmh-generated-classes, jmh-generated-sources)
fix broken jmh metadata files (BenchmarkList, CompilerHints)
fix jmh command line jar (inline dependencies with shadow plugin)
fix jmh task for root scope (stop generate dummy jar)
cleanup redundant out directory generated by IDEA
remove slf4j and log4j dependencies (replace with slf4j-nop logger)
add visual jmh report

### CODE REVIEW

**Comment by qweek** [comment]
Refactor #401

**Comment by yschimke** [comment]
I think @robertroeser knows the benchmark tests

@qweek what's the command for the visual JHM report? Curious to try running these.

**Comment by qweek** [comment]
Report created after jmh task
`tasks.jmh.finalizedBy tasks.jmhReport`

**Comment by qweek** [comment]
I'm also evaluating additional reports and verifications (including test coverage)
**Tools** section in [feature/ci/README.md](https://github.com/qweek/rsocket-java/blob/feature/ci/README.md)

**Comment by qweek** [comment]
Please restart build, looks like problem in CI
Another Travis instance is ok [Build Status](https://travis-ci.org/qweek/rsocket-java)

**Pull request merged**
