### PR TITLE
Gradle4 exploration

### PR DESCRIPTION
**Pull request by yschimke**
Won't land without snapshot publishing working, and hopefully release publishing also.

### CODE REVIEW

**Comment by yschimke** [comment]
Currently building maven items.  Bintray plugin authentication is working, but failing because the project isn't configured correctly somehow

```
* What went wrong:
Execution failed for task ':rsocket-core:bintrayUpload'.
> Could not create version '0.9-SNAPSHOT': HTTP/1.1 400 Bad Request [message:Unable to create version 0.9-SNAPSHOT at 'rsocket-admin/RSocket/rsocket-core']

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.
```

**Comment by yschimke** [comment]
@robertroeser @benjchristensen I think this is now functional for publishing both 

snapshots

https://oss.jfrog.org/oss-snapshot-local/io/rsocket/rsocket-core/0.9-SNAPSHOT/rsocket-core-0.9-20170715.185448-51.pom

releases

https://bintray.com/rsocket-admin/RSocket/rsocket-core

**Comment by yschimke** [comment]
I don't think version incrementing is working, so snapshots will be stuck on 0.9-SNAPSHOT, but releases should take the tag version.  Feel free to fix up mistakes, suggest changes or test yourself.

**Comment by yschimke** [comment]
Looks like it isn't sending a single package like reactivesocket-java was

https://bintray.com/reactivesocket/ReactiveSocket/reactivesocket-java#files/io/reactivesocket
https://bintray.com/rsocket-admin/RSocket/rsocket-core#files/io/rsocket/rsocket-core

**Comment by robertroeser** [comment]
@yschimke just checked this out. Looks great - builds much faster. What's missing to make this land?

**Comment by yschimke** [comment]
I think I will land it. But release publishing not working end to end. Closer though

**Comment by yschimke** [comment]
@robertroeser landed and snapshots published, but tagged publishing needs attention still

https://travis-ci.org/rsocket/rsocket-java/builds/259649099

**Pull request merged**
