### PR TITLE
adds proxy RSocket for WeightedStatsRequestInterceptor

### PR DESCRIPTION
**Pull request by spencergibb**
Signed-off-by: Spencer Gibb sgibb@pivotal.io

### CODE REVIEW

**Review by rstoyanchev — CHANGES_REQUESTED** [review]
Sorry for the slow response. 

I'm not sure if this needs to be tied to the interceptor. Perhaps something like this would make it more generally useful:
```java
public class WeightedStatsRSocketProxy extends RSocketProxy implements WeightedStats {

	private final WeightedStats stats;


	public WeightedStatsRSocketProxy(RSocket source, WeightedStats stats) {
		super(source);
		this.stats = stats;
	}

	@Override
	public double higherQuantileLatency() {
		return this.stats.higherQuantileLatency();
	}

	@Override
	public double lowerQuantileLatency() {
		return this.stats.lowerQuantileLatency();
	}

	@Override
	public int pending() {
		return this.stats.pending();
	}

	@Override
	public double predictedLatency() {
		return this.stats.predictedLatency();
	}

	@Override
	public double weightedAvailability() {
		return this.stats.weightedAvailability();
	}
}
```

**Comment by spencergibb** [comment]
In conversations with @OlegDokuka, the idea was that the class wouldn't be public.

**Comment by spencergibb** [comment]
@rstoyanchev maybe a package protected class, but with the static creator in the interceptor still?

**Comment by rstoyanchev** [comment]
> maybe a package protected class, but with the static creator in the interceptor still?

Isn't that what's currently proposed? 

How about exposing via default method on `WeightedStats`, something like:
```java
default RSocket wrap(RSocket rsocket) {
    return new WeightedStatsRSocketProxy(rsocket, this); // instantiate package private class
}
```

**Comment by spencergibb** [comment]
Done @rstoyanchev

**Review by rstoyanchev — APPROVED** [review]

**Pull request merged**
