### PR TITLE
netty transports: close connections on server dispose

### PR DESCRIPTION
**Pull request by mostroverkhov**
should fix https://github.com/rsocket/rsocket-java/issues/603

### CODE REVIEW

**Comment by robertroeser** [comment]
I don't think we should be creating channel groups or change the executors - esp. with reactor-netty which sets up it's own event loops. This could also screw up other netty instances. When you receive a connection you could just subscribe to an mono processor and that when it completes it calls dispose.

**Comment by smaldini** [comment]
I would advise caution on that change - Maybe we should look at the problem in a different fashion, e.g. you need to dispose a server mostly in test scenarios. Should we provide rsocket-test to help with this ?
The workaround is not too hard neither, disposing the resources (and shutting down the event loop group) will force the close in an `@After` callback .

**Comment by mostroverkhov** [comment]
@smaldini In that case I'd suggest removing `dispose` on rsocket server, given that all transports implemented are based on netty

**Comment by sleoniy** [comment]
Still having this issue, it appears PR is still open.

**Comment by OlegDokuka** [comment]
Closing in favor of native graceful shutdown support in Reactor-Netty. See https://github.com/reactor/reactor-netty/releases and https://github.com/reactor/reactor-netty/pull/1034

**Pull request closed without merging**
