### PR TITLE
Revert "Performance Optimization Session (#682)"

### PR DESCRIPTION
**Pull request by mostroverkhov**

### CODE REVIEW

**Comment by OlegDokuka** [comment]
Hey.

What is the reason for doing that?

**Comment by mostroverkhov** [comment]
The reason is It makes soak test unstable, probably due to impl does not respect downstream demand request, and improper use of `lazySet`

**Comment by OlegDokuka** [comment]
Let me take a look at that, may be I will be able to provide a fix quickly

**Comment by OlegDokuka** [comment]
Alright. I see the problem. Totally agree - my bad. Going to fix that later cuz it  is going to take a while

**Pull request merged**
