### PR TITLE
Select RSocket from the pool when retrying requestChannel

### PR DESCRIPTION
**Pull request by Alex079**
`rSocketPool.select()` in method `requestChannel` should be called on each subscription as it is done in other methods of the class.

### Motivation:

When server restarts while client is still connected, `LoadbalanceRSocketClient` is not able to reconnect when retrying `requestChannel` Flux. Retry fails with the error "Only a single Subscriber allowed".

### Modifications:

Wrap `rSocketPool.select()` in Mono.

### Result:

Retrying `requestChannel` Flux should trigger connection attempt.

### Target branch:

I cannot create a new base branch in rsocket-java as described in contribution guidelines. Creating the PR on master instead.

### CODE REVIEW

**Comment by OlegDokuka** [comment]
Hi @Alex079!

Indeed it is a bug. Do you mind writing a test for that as well? 

Thanks,
Oleh

**Comment by Alex079** [comment]
hello @OlegDokuka,

I will find some time to finish it this week.

Thanks,
Alex

**Comment by Alex079** [comment]
I have added the test. Could you please check?

**Comment by OlegDokuka** [comment]
@Alex079 can you please rebase on 1.1.x branch.
Thanks

**Comment by OlegDokuka** [comment]
closed in favor of #1086

**Pull request closed without merging**
