### PR TITLE
URI Registry

### PR DESCRIPTION
**Pull request by yschimke**
Designed to allow for things like CLI or load test clients that could specify a target purely by a URI supported by a provider on the classpath

### CODE REVIEW

**Comment by yschimke** [comment]
cc @tmontgomery

**Comment by yschimke** [comment]
TODO still support aeron + local + websocket + tcp (server)

**Comment by tmontgomery** [comment]
Looks good to me. Each transport has their own URI scheme. So, should be straight forward.

**Comment by yschimke** [comment]
@tmontgomery I'll complete and then get a final shipit.  Thanks

**Comment by yschimke** [comment]
Merging - based on earlier review.  Feel free to add and review comments and I'll address.

**Pull request merged**
