### PR TITLE
add git attributes

### PR DESCRIPTION
**Pull request by qweek**
add .gitattributes for normalize line ending

### CODE REVIEW

**Comment by yschimke** [comment]
I'm not sold on this, whether it it worthwhile adding or default for java files should be "lf" anyway.

Happy to hear from others, particularly any windows devs.  Are you on Windows?

**Comment by qweek** [comment]
This is the recommended setting on Windows because it ensures that your repository can be used on other platforms [mind-the-end-of-your-line](http://adaptivepatchwork.com/2012/03/01/mind-the-end-of-your-line/)
> tell git to detect all text files and automatically normalize them (convert CRLF to LF)

**Comment by yschimke** [comment]
Can you give an example of other popular gradle java projects that apply this?

**Comment by qweek** [comment]
[ReactiveX/RxJava](https://github.com/ReactiveX/RxJava/blob/2.x/.gitattributes)
[google/guava](https://github.com/google/guava/blob/master/.gitattributes)
[mockito/mockito](https://github.com/mockito/mockito/blob/release/2.x/.gitattributes)

**Pull request merged**
