### PR TITLE
adds class check for discarded values

### LINKED ISSUE #1077: SendUtils onDiscard handler class cast exception
I'm using RSocket Java with Spring Webflux and RSocket JS in the front-end, using `REQUEST_STREAM` with an infinite Kafka source. The returned Flux receives quite a lot of small messages and does quite a bit of filtering and buffering. [The relevant code in `SendUtils`](https://github.com/rsocket/rsocket-java/blob/e31038f04e8bfc7b9c3a9a2b3a12fd578ed02a40/rsocket-core/src/main/java/io/rsocket/core/SendUtils.java#L41-L51) does an unchecked cast of each discarded object to a `ReferenceCounted` which seems to throw a class cast exception that is caught and ignored.  
The problem is that due to the sheer amount of objects being discarded (due to filtering and discarded buffers on disconnect), this uses up a substantial amount of CPU resources looking at the profiler.

profiler

The returned Fluxes are scheduled on `Schedulers.boundedElastic()`, and for some reason entire threads are started up just for this exception:
flamegraph

## Expected Behavior
Not use up so much CPU resources

## Actual Behavior
Uses a lot of CPU resources

## Possible Solution
Not exactly sure, but perhaps an `instanceof` check:
```java
if (data instanceof ReferenceCounted) ((ReferenceCounted) data).release();
```

## Your Environment

* RSocket version(s) used: rsocket-core:1.1.3, rsocket-transport-netty:1.1.3
* Other relevant libraries versions (eg. `netty`, ...): Spring Webflux 5.3.23
* Platform (eg. JVM version (`javar -version`) or Node version (`node --version`)): 17
* OS and version (eg `uname -a`): Happens on all tested platforms (Debian, Mac)

### PR DESCRIPTION
**Pull request by OlegDokuka**
closes #1077

### CODE REVIEW

**Comment by zhou-hao** [comment]
The version `1.1.4` in maven  repository does not contains this commit ? 

image

**Comment by VictoryWangCN** [comment]
@OlegDokuka The version 1.1.5 in maven repository does not contains this commit ?

**Comment by OlegDokuka** [comment]
> @OlegDokuka The version 1.1.5 in maven repository does not contains this commit ?

it should. do you observe any issues related to that?

**Comment by VictoryWangCN** [comment]
@OlegDokuka I found that io/rsocket/core/DefaultRSocketClient.java in sources.jar does not contain the content.

image

**Comment by VictoryWangCN** [comment]
@OlegDokuka 1.1.5 still throw ClassCastException 
```
java.lang.ClassCastException: class org.springframework.core.io.buffer.NettyDataBuffer cannot be cast to class io.netty.util.ReferenceCounted (org.springframework.core.io.buffer.NettyDataBuffer and io.netty.util.ReferenceCounted are in unnamed module of loader 'app')
	at java.base/java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[na:na]
	at java.base/java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[na:na]
	at reactor.core.publisher.Operators.onDiscard(Operators.java:441) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.MonoZip$ZipInner.cancel(MonoZip.java:388) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.MonoZip$ZipCoordinator.cancel(MonoZip.java:272) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.cancel(FluxMap.java:300) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.cancel(FluxContextWrite.java:141) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.cancel(FluxContextWrite.java:141) ~[reactor-core-3.4.34.jar:3.4.34]
	at io.rsocket.core.DefaultRSocketClient$FlatMapMain.cancel(DefaultRSocketClient.java:331) ~[rsocket-core-1.1.5.jar:na]
	at io.rsocket.core.DefaultRSocketClient$FlattingInner.cancel(DefaultRSocketClient.java:463) ~[rsocket-core-1.1.5.jar:na]
	at reactor.core.publisher.FluxMap$MapSubscriber.cancel(FluxMap.java:169) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.FluxMap$MapSubscriber.cancel(FluxMap.java:169) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.Operators.terminate(Operators.java:1277) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.cancel(MonoSubscribeOn.java:210) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.BlockingSingleSubscriber.dispose(BlockingSingleSubscriber.java:70) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:123) ~[reactor-core-3.4.34.jar:3.4.34]
	at reactor.core.publisher.Mono.block(Mono.java:1766) ~[reactor-core-3.4.34.jar:3.4.34]
```

may cause by 
https://github.com/reactor/reactor-core/pull/3209

```java
// org.springframework.messaging.rsocket.DefaultRSocketRequester.DefaultRequestSpec#firstPayload
private Mono<Payload> firstPayload(Mono<DataBuffer> encodedData) {
			return Mono.zip(encodedData, this.metadataEncoder.encode())
					.map(tuple -> PayloadUtils.createPayload(tuple.getT1(), tuple.getT2()))
					.doOnDiscard(DataBuffer.class, DataBufferUtils::release)
					.doOnDiscard(Payload.class, Payload::release);
		
```

**Pull request merged**
