### PR TITLE
Updated username length for new spec (uint8 vs uint16)

### PR DESCRIPTION
**Pull request by freelancer1845**
As I stumbled over this when implementing the security extension and testing it with spring-boot. Just in case this has been forgotten.

Now reads/writes username length as uint16.
 
The spec was changed in that commit:
https://github.com/rsocket/rsocket/commit/2687daae258f3688e769dbaddb426c65d7420acd

### CODE REVIEW

**Review by OlegDokuka — APPROVED** [review]
LGTM

**Comment by OlegDokuka** [comment]
@freelancer1845 can you please make sure that the PR is based against 1.0.x and is up to date.

**Comment by freelancer1845** [comment]
Oh now I see what happend there...
My fork is somehow way behind (didn't remember I created it)

I think its easier for me to create a new pull request to resolve this... I'll do that tomorrow^^

sorry..

**Comment by OlegDokuka** [comment]
np

**Pull request closed without merging**
